In [3]:
import numpy as np 

In [13]:
mat1 = np.zeros((3,5))
mat2 = np.ones((5,5))
np.savez('np_files',Ones_Mat=mat2,Zeros_mat=mat1)


In [14]:
with np.load('np_files.npz') as file:
  mat1=file['Ones_Mat']
  mat1=file['Zeros_mat']
print(mat1)
print(mat2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
