In [8]:
import numpy as np

In [10]:
arr = np.array([1,2,3,4,5])
print(type(arr))

<class 'numpy.ndarray'>


In [12]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [17]:
import numpy as np
#0D
arr = np.array(42)
print(arr)
#---------
#1D
print("-"*40)
arr = np.array([1,2,3,4,5])
print(arr)
#---------
#2D
print("-"*40)
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
#---------
#3D
print("-"*40)
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],
                [[13,14,15],[16,17,18]],[[19,20,22],[23,24,25]]]
                )
print(arr)



42
----------------------------------------
[1 2 3 4 5]
----------------------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
----------------------------------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 22]
  [23 24 25]]]


In [32]:
print("-"*40)
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],
                [[13,14,15],[16,17,18]],[[19,20,22],[23,24,25]]]
                )
print(arr[0,0,0])



----------------------------------------
1


In [38]:
arr = np.array([1,2,3,4,5], ndmin = 5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


In [39]:
arr = np.array([1,2,3,4,5])
print(arr[2]+arr[3])

7


In [41]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row', arr[0,1])

2nd element on 1st row 2


In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [44]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element from 2nd dim: ' , arr[1,-1])

Last element from 2nd dim:  10


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[4::2])
#arr [ start : end : step ]

[5 7]


In [46]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [51]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [52]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [57]:
arr = np.array([1,2,3,4])
print(arr.dtype)


int64


In [60]:
arr = np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [ ]:
arr = np.array([1,2,3,4] , dtype='i' )
arr.dtype

dtype('int32')

In [70]:
arr = np.array([1.1,2.1,3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


#i b S u f c m M O U V

In [71]:
arr = np.array([1.1,2.1,3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [ ]:
# when i write a 'b' he return int8 
arr = np.array([1,0,3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [80]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0]= 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [83]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [84]:
arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] = 31
print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [85]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [92]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
print(arr.ndim)
print(arr)
print(arr[0,1:4])


(2, 4)
2
[[1 2 3 4]
 [5 6 7 8]]
[2 3 4]


In [95]:
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print(arr.ndim)
print(arr.shape)

[[[[[1 2 3 4]]]]]
5
(1, 1, 1, 1, 4)


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [100]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]
newarr = arr.reshape(2,3,2)
print(newarr)
print(arr.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(12,)


In [102]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [104]:
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [107]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr.shape)
print(newarr)

(6,)
[1 2 3 4 5 6]


In [108]:
arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
for x in arr :
    print(x)

[1 2 3]
[4 5 6]


In [112]:
arr = np.array([[1,2,3],[4,5,6]])
for x in arr :
    for y in x:
        print(y,end =' '*2)
    print("\n")


1  2  3  

4  5  6  



In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [119]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print('\n')
    for y in x:
        print('\n')
        for z in y:
            print(z,end=' ')





1 2 3 

4 5 6 



7 8 9 

10 11 12 

In [122]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [127]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
for x in np.nditer(arr,flags = ['buffered'], op_dtypes = 'S'):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')
np.bytes_(b'9')


In [133]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.astype('i')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [135]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [139]:
for idx,x in np.ndenumerate(arr):
    print(idx ," " , x)

(0, 0)   1
(0, 1)   2
(0, 2)   3
(0, 3)   4
(1, 0)   5
(1, 1)   6
(1, 2)   7
(1, 3)   8


In [ ]:
i = 'ahmed'
for idx,x in enumerate(i):
    print(idx,' ',x)

0   a
1   h
2   m
3   e
4   d


In [147]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr2,arr1))
print(arr)
print(arr.reshape(2,3))

[4 5 6 1 2 3]
[[4 5 6]
 [1 2 3]]


In [155]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [166]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1,arr2),axis = 1)
print(arr)


[[1 4]
 [2 5]
 [3 6]]


In [175]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1,arr2))
arr3= np.concatenate((arr1,arr2))
print(arr)
print(arr3)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [176]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [180]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.concatenate((a,b), axis=1))

[[1 2 5 6]
 [3 4 7 8]]


In [185]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.stack((a,b)))

[[1 2 3]
 [4 5 6]]


In [186]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [187]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [196]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)
newarr[2][1]

[array([1, 2]), array([3, 4]), array([5, 6])]


np.int64(6)

In [197]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [198]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [199]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [204]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [206]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=0)

merged = newarr[0].reshape(-1)

print(merged)

[1 2 3 4 5 6]


In [207]:
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [208]:
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [209]:
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6]),)


In [212]:
arr = np.array([6, 7, 8, 9,7])

x = np.searchsorted(arr, 7)
y = np.where(arr == 7)
print(x)
y

1


(array([1, 4]),)

In [214]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)
print(arr.size)

2
4


In [ ]:
#the location where it should  be inserted
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


In [216]:
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [217]:
arr = np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [218]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [219]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [220]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [224]:
arr = np.array([41,42,43,44])
filter_arr = []
for element in arr:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
print(arr)
print(filter_arr)
print(newarr)

[41 42 43 44]
[False, False, True, True]
[43 44]


In [226]:
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]
print(arr)
print(filter_arr)
print(newarr)

[41 42 43 44]
[False, True, False, True]
[42 44]


In [227]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
