In [2]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [3]:
zeroes = np.zeros((2,3))
print(zeroes)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
ones = np.ones((3,2),dtype ='i')
ones

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [5]:
range_array = np.arange(10)
print(range_array)
print(range_array.reshape(2,5))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
range_step = np.arange(0,10,2)
print(range_step)

[0 2 4 6 8]


In [7]:
linspace_array = np.linspace(0,1,5)
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


In [8]:
random_array = np.random.rand(3,3)
print(random_array)

[[0.15824674 0.39646154 0.44461652]
 [0.75368746 0.24347699 0.1141117 ]
 [0.12866309 0.54772816 0.7237849 ]]


In [9]:
random_integers = np.random.randint(1,10,(2,2))
print(random_integers)

[[6 9]
 [1 5]]


In [10]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [11]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr + 10)

[[11 12 13]
 [14 15 16]]


In [27]:
arr1 = np.array([[1,2],
                 [3,4]])
"""
19  22
43  50
"""
arr2 = np.array([[5,6],
                 [7,8]])
# print(np.concatenate((arr1,arr2),axis=1))
print(np.dot(arr1,arr2))


[[19 22]
 [43 50]]


In [ ]:
arr = np.array([1,2,3,4,5])
print(np.mean(arr))
print(np.sum(arr))


3.0
15


In [31]:
arr = np.array([[1,2],[3,4]])
print(np.mean(arr))
print(np.sum(arr))


2.5
10


In [32]:
print(np.max(arr))
print(np.min(arr))

4
1


In [34]:
diagonal_matrix = np.diag([1,2,4])
print(diagonal_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 4]]


In [47]:
on = np.arange(1,101)
print(on.reshape(10,10))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [48]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
upper_triangular = np.array([[1,2,3],
                             [0,5,6],
                             [0,0,9]])
print('Upper Triangular Matrix: \n',upper_triangular)

Upper Triangular Matrix: 
 [[1 2 3]
 [0 5 6]
 [0 0 9]]


In [53]:
matrix = np.array([[1,2,3],
                   [4,5,6]])
transpose_matrix = np.transpose(matrix)
print("Original matrix:\n",matrix)
print("Original matrix:\n",transpose_matrix)
print("Original matrix:\n",matrix.T)


Original matrix:
 [[1 2 3]
 [4 5 6]]
Original matrix:
 [[1 4]
 [2 5]
 [3 6]]
Original matrix:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
trace = np.trace(matrix)
print(trace)# sum the diagonal of matrix

15


In [57]:
matrix = np.array([[4,6],
                    [3,8]])
determinant = np.linalg.det(matrix)
print(determinant)

14.000000000000004


In [59]:
matrix = np.array([[1,2],
                    [3,4]])
inver_matrix = np.linalg.inv(matrix)
print("Invers of Matrix:\n",inver_matrix)

Invers of Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [65]:
matrix = np.array([ [1,2,3],
                    [4,5,6],
                    [7,8,9]])
rank = np.linalg.matrix_rank(matrix)
print(rank)

2


In [70]:
print(matrix[1]*2-matrix[0])

[7 8 9]
