# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [18]:
import numpy as np
import difflib

def normalize_mode(mode):
    mode = mode.lower()
    VALID_MODES = ['zeros', 'ones', 'full', 'identity']
    match = difflib.get_close_matches(mode, VALID_MODES, n=1, cutoff=0.6)
    if match:
        return match[0] 
    else:
        return mode  

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    if not isinstance(mode,str) : 
        raise ValueError("mode should be string")    
    mode = mode.lower()
    mode = normalize_mode(mode)
    if mode == 'zeros':
        return np.zeros(shape)

    elif mode == 'ones':
        return np.ones(shape)

    elif mode == 'full':
        if value is None:
            raise ValueError("You must provide a value for 'full' mode")
        return np.full(shape, value)

    elif mode == 'identity':
        if not isinstance(shape, int):
            raise ValueError("Shape must be an integer for identity matrix")
        return np.identity(shape)

array_factory('zero',(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [ ]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        # Convert inputs to ndarray to ensure they are processed as Tensors 
        # arr = np.array(data1)

        arr1 = # TODO
        arr2 = # TODO

        # Rule: Change the shape of arr1 to new_shape 
        # Common usage: turning a vector (1D) into a matrix (2D)  by using reshape function 
        reshaped_arr1 = # TODO

        # Rule: Vertical Stacking (vstack) 
        # Requirement: Both matrices must have the same number of columns
        combined_dataset = # TODO

        return # TODO

    except ValueError as e:
        # Handle cases where reshape size doesn't match or stack columns don't match
        raise ValueError(f"Company-grade Error: {e}")

In [ ]:
import numpy as np
def secure_reshape_and_stack(data1,data2,new_shape):
    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)
        reshaped_arr1 = arr1.reshape(new_shape)
        if arr2.ndim ==1:
            arr2 = arr2.reshape(1,-1)
        if reshaped_arr1.shape[1] != arr2.shape[1]:
            raise ValueError("Column mismatch for vertical stacking")
        combined_dataset = np.vstack((reshaped_arr1, arr2))
        return combined_dataset
    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")
data1 = [1,2,3,4]
data2 = [[5,6],
         [7,8]]
result = secure_reshape_and_stack(data1, data2, (2,2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [ ]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold) 
    and replaces them with a new value.
    """
    # 1. Convert input to a numpy array (ndarray)
    arr = # TODO
    # 2. Define the condition: elementwise comparison 
    # This creates a Boolean numpy array 
    condition = # TODO
    
    # 3. Apply Modification using np.where() 
    # np.where(condition, value_if_true, value_if_false)
    modified_arr = #TODO
    
    return modified_arr

TestCase

In [ ]:
# Regional Branch A (Flat sales data)
branch_a = [1, 2, 3, 4, 5, 6] 

# Regional Branch B (Already formatted 2x3 matrix)
branch_b = [[7, 8, 9], 
            [10, 11, 12]]

# Reshape A to 2x3 and stack with B
final_report = apply_threshold(branch_a, branch_b, (2, 3))
print(final_report)
# Resulting shape: (4, 3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


: 

In [4]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


array([  1, -20, -20])

In [ ]:
i = 10
for j in range()

0
1
2
3
4
5
6
7
8
9


In [ ]:
nums = [1,2,3]
for n 