In [ ]:
import pandas as pd

In [ ]:
s=pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
s=pd.Series([1,2,3,4],index=['a','b','c','d'])
s

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
data=[[1,444,'abc'],
      [2,555,'def'],
      [3,666,'ghi'],
      [4,4444,'xyz']
      ]
df=pd.DataFrame(data,columns=['id','salary','dept'])
df
display(df)
df.columns
index = ['R1','R2','R3','R4']
df.index=index
df

id  salary dept
0   1     444  abc
1   2     555  def
2   3     666  ghi
3   4    4444  xyz

id  salary dept
R1   1     444  abc
R2   2     555  def
R3   3     666  ghi
R4   4    4444  xyz

In [ ]:
data_dic = {'id':[1,2,3,4],
            'salary':[444,555,666,444],
            'dept':['abd','def','ghi','xyz']
}
df_1=pd.DataFrame(data_dic)
df_1

id  salary dept
0   1     444  abd
1   2     555  def
2   3     666  ghi
3   4     444  xyz

In [ ]:
data=[[1,444,'abc'],
      [2,555,'def'],
      [3,666,'ghi'],
      [4,4444,'xyz']#444 not 4444
      ]
df=pd.DataFrame(data,columns=['id','salary','dept'])
df
display(df)
df.columns
index = ['R1','R2','R3','R4']
df.index=index
df

id  salary dept
0   1     444  abc
1   2     555  def
2   3     666  ghi
3   4    4444  xyz

id  salary dept
R1   1     444  abc
R2   2     555  def
R3   3     666  ghi
R4   4    4444  xyz

In [ ]:
df.dtypes

id         int64
salary     int64
dept      object
dtype: object

In [ ]:
def chk(df,ty):
  return df[ty]

In [ ]:
df['salary'].dtypes

dtype('int64')

In [ ]:
df['dept']=df['dept'].astype('category')

In [ ]:
df['dept'].dtype

CategoricalDtype(categories=['abc', 'def', 'ghi', 'xyz'], ordered=False, categories_dtype=object)

In [ ]:
df.dtypes

id           int64
salary       int64
dept      category
dtype: object

In [ ]:
df.head(2)

id  salary dept
R1   1     444  abc
R2   2     555  def

In [ ]:
df.tail(2)

id  salary dept
R3   3     666  ghi
R4   4    4444  xyz

In [ ]:
df.describe()

id       salary
count  4.000000     4.000000
mean   2.500000  1527.250000
std    1.290994  1946.610965
min    1.000000   444.000000
25%    1.750000   527.250000
50%    2.500000   610.500000
75%    3.250000  1610.500000
max    4.000000  4444.000000

25% = Q1   , 50%

In [ ]:
df.describe(include='category')

dept
count     4
unique    4
top     abc
freq      1

In [ ]:
df.index

Index(['R1', 'R2', 'R3', 'R4'], dtype='object')

In [ ]:
df.columns

Index(['id', 'salary', 'dept'], dtype='object')

In [ ]:
df['salary'].unique()# he give you the unique values like 444 but i say there 444 and 4444 my fall

array([ 444,  555,  666, 4444])

In [ ]:
df['salary'].nunique()#the number or uniques values

4

In [ ]:
df['salary'].max() # should be 444

4444

In [ ]:
df['salary'].min()

444

In [ ]:
df['salary'].idxmax()# should be R3 but i say R4 4444 by false

'R4'

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, R1 to R4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   id      4 non-null      int64   
 1   salary  4 non-null      int64   
 2   dept    4 non-null      category
dtypes: category(1), int64(2)
memory usage: 476.0+ bytes


In [ ]:
df['salary'].sum()#6109-4000=2109

np.int64(6109)

In [ ]:
df['salary'].values

array([ 444,  555,  666, 4444])

In [ ]:
df.values

array([[1, 444, 'abc'],
       [2, 555, 'def'],
       [3, 666, 'ghi'],
       [4, 4444, 'xyz']], dtype=object)

In [ ]:
df.replace(555,'Ali')


id salary dept
R1   1    444  abc
R2   2    Ali  def
R3   3    666  ghi
R4   4   4444  xyz

In [ ]:
df.replace(4444,444)

id  salary dept
R1   1     444  abc
R2   2     555  def
R3   3     666  ghi
R4   4     444  xyz

In [ ]:
df

id  salary dept
R1   1     444  abc
R2   2     555  def
R3   3     666  ghi
R4   4    4444  xyz

In [ ]:
df.replace({4444:'Ali','abc':555})

/tmp/ipython-input-1750500244.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df.replace({4444:'Ali','abc':555})


id salary dept
R1   1    444  555
R2   2    555  def
R3   3    666  ghi
R4   4    Ali  xyz

In [ ]:
x=df['salary'].iloc[3]
df=df.replace(x,444)
df

id  salary dept
R1   1     444  abc
R2   2     555  def
R3   3     666  ghi
R4   4     444  xyz

In [ ]:
df.iloc[2,1]# x,y  الصف والعمود

np.int64(666)

In [ ]:
df['salary'].iloc[0:2]

R1    444
R2    555
Name: salary, dtype: int64

In [ ]:
df.iloc[:,0:2]

id  salary
R1   1     444
R2   2     555
R3   3     666
R4   4     444

In [ ]:
df

id  salary dept
R1   1     444  abc
R2   2     555  def
R3   3     666  ghi
R4   4     444  xyz

In [ ]:
df.iloc[:,:-1]

id  salary
R1   1     444
R2   2     555
R3   3     666
R4   4     444

In [ ]:
null = df.isnull()

In [ ]:
null

id  salary   dept
R1  False   False  False
R2  False   False  False
R3  False   False  False
R4  False   False  False

In [ ]:
null = df.isnull().sum()
null

id        0
salary    0
dept      0
dtype: int64

In [ ]:
import numpy as np
data=[[1,444,'abc'],
      [np.nan,555,'def'],
      [3,666,'ghi'],
      [4,np.nan,'xyz']#444 not 4444
      ]
df=pd.DataFrame(data,columns=['id','salary','dept'])
df

id  salary dept
0  1.0   444.0  abc
1  NaN   555.0  def
2  3.0   666.0  ghi
3  4.0     NaN  xyz

In [ ]:
null = df.isnull().sum()
null


id        1
salary    1
dept      0
dtype: int64

In [ ]:
pd.DataFrame(null).T # transpose

id  salary  dept
0   1       1     0

In [ ]:
df.dropna()#to remove the row that have nulls

id  salary dept
0  1.0   444.0  abc
2  3.0   666.0  ghi

In [ ]:
df.dropna(subset=['salary'])

id  salary dept
0  1.0   444.0  abc
1  NaN   555.0  def
2  3.0   666.0  ghi

In [ ]:
df.dropna(axis=1)

dept
0  abc
1  def
2  ghi
3  xyz

In [ ]:
df.drop(['id'],axis=1) # ليه لما كانت axis=0 عمل error لأنه كان بيدور على salary

salary dept
0   444.0  abc
1   555.0  def
2   666.0  ghi
3     NaN  xyz

In [ ]:
mean=df['salary'].mean()

In [ ]:
df['salary']=df['salary'].fillna(value=mean)#replace the null

In [ ]:
df

id  salary dept
0  1.0   444.0  abc
1  NaN   555.0  def
2  3.0   666.0  ghi
3  4.0   555.0  xyz

In [ ]:
Header_col = ['index','gender','dept','potal_code']
data=pd.read_table('http://bit.ly/movieusers%27',sep='|',header=None,names=Header_col)#header ده عشان اول صف مش عنوان
data

index gender           dept potal_code
1       24      M     technician      85711
2       53      F          other      94043
3       23      M         writer      32067
4       24      M     technician      43537
5       33      F          other      15213
..     ...    ...            ...        ...
939     26      F        student      33319
940     32      M  administrator      02215
941     20      M        student      97229
942     48      F      librarian      78209
943     22      M        student      77841

[943 rows x 4 columns]

In [ ]:
user_info=pd.read_csv('http://bit.ly/uforeports')


In [ ]:
user_info.head()

City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [ ]:
user_info.shape

(18241, 5)

In [ ]:
'ab'+'cd'

'abcd'

In [ ]:
user_info['location']= user_info.City+' '+user_info.State
user_info.head()

City Colors Reported Shape Reported State             Time  \
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00   
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00   
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00   
3               Abilene             NaN           DISK    KS   6/1/1931 13:00   
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00   

                  location  
0                Ithaca NY  
1           Willingboro NJ  
2               Holyoke CO  
3               Abilene KS  
4  New York Worlds Fair NY

In [ ]:
user_info.to_csv('test.csv')#بيخزنة ك csv file

In [ ]:
user_info.rename(colums={'Colors Reported':'Colors_Reported'})

TypeError: DataFrame.rename() got an unexpected keyword argument 'colums'

In [ ]:
user_info.columns = user_info.columns.str.replace(' ', '_')
user_info.head()
#لو عابب أشبيل ال spacce في ال rows ممكن عبر ال slicing or for

City Colors_Reported Shape_Reported State             Time  \
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00   
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00   
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00   
3               Abilene             NaN           DISK    KS   6/1/1931 13:00   
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00   

                  location  
0                Ithaca NY  
1           Willingboro NJ  
2               Holyoke CO  
3               Abilene KS  
4  New York Worlds Fair NY

In [ ]:
user_info.rename({'Colors Reported':'Colors_Reported'}, axis=1, inplace=True) # سبب ال erro نسخت  panda قديمة اللي عندي
user_info

City Colors_Reported Shape_Reported State  \
0                    Ithaca             NaN       TRIANGLE    NY   
1               Willingboro             NaN          OTHER    NJ   
2                   Holyoke             NaN           OVAL    CO   
3                   Abilene             NaN           DISK    KS   
4      New York Worlds Fair             NaN          LIGHT    NY   
...                     ...             ...            ...   ...   
18236            Grant Park             NaN       TRIANGLE    IL   
18237           Spirit Lake             NaN           DISK    IA   
18238           Eagle River             NaN            NaN    WI   
18239           Eagle River             RED          LIGHT    WI   
18240                  Ybor             NaN           OVAL    FL   

                   Time                 location  
0        6/1/1930 22:00                Ithaca NY  
1       6/30/1930 20:00           Willingboro NJ  
2       2/15/1931 14:00               Holyoke CO  
3        6/1/1931 13:00               Abilene KS  
4       4/18/1933 19:00  New York Worlds Fair NY  
...                 ...                      ...  
18236  12/31/2000 23:00            Grant Park IL  
18237  12/31/2000 23:00           Spirit Lake IA  
18238  12/31/2000 23:45           Eagle River WI  
18239  12/31/2000 23:45           Eagle River WI  
18240  12/31/2000 23:59                  Ybor FL  

[18241 rows x 6 columns]